# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # --- ESTA ES LA PARTE QUE CAMBIA ---
  - job_name: "minecraft"
    static_configs:
      # Apuntamos al servicio 'minecraft' en el puerto que usa tu MOD
      # Si tu mod usa un puerto diferente a 9225, cámbialo aquí.
      - targets: ["minecraft-exporter:9150"]
