name = "Sofware Fauna"
author = "alraro"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "726006823ceb316f2580222ab6aec3ac2dcada991504a386d4212992ea333b01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
