name = "Sofware Fauna"
author = "alraro"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f3627872c0aa1cee27bec33af0ae812805b0ebecf42994a914229ee7f8bb74e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
